### ISSUE TITLE
Backup package 100% strings completed (string-arrays to translate)

### ISSUE THREAD

**Issue by MarkH-UK** [MiCode/i18n_miui#10]
Imran + translation team.

Please review https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Backup/res/values-ms/strings.xml

There are 'string-array' items which require translations. Please ignore any which have comments or lines saying translatable="false" or 'do not translate'. This also applies to other issues I will open for packages for review.

Mark

**Comment by imranz** [comment]
complete translated Backup strings xml
