### ISSUE TITLE
Calendar package (review plurals and translate arrays.xml)

### ISSUE THREAD

**Issue by MarkH-UK** [MiCode/i18n_miui#16]
Imran to review Calendar package:

https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Calendar/res/values-ms/strings.xml

Some elements require translation in plurals etc.

Translation also required for: https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Calendar/miui_res/values-ms/arrays.xml

https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Calendar/miui_res/values-ms/strings.xml

**Comment by imranz** [comment]
fix translation calendar strings xml
