### ISSUE TITLE
Email package 100% strings complete (review string-array + plurals)

### ISSUE THREAD

**Issue by MarkH-UK** [MiCode/i18n_miui#24]
Imrans team to review these files for translation...

Review / Translate string arrays here: https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Email/miui_res/values-ms/strings.xml

and also https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Email/res/values-ms/strings.xml

**Comment by imranz** [comment]
fix translation in Email package strings xml done
