### ISSUE TITLE
MiuiMusic (review plurals and string-arrays)

### ISSUE THREAD

**Issue by MarkH-UK** [MiCode/i18n_miui#33]
@imranz please review plurals and string-arrays in MiuiMusic/phone/res/values-ms/strings.xml

**Comment by MarkH-UK** [comment]
Need to update convert.sh to handle overlay

**Comment by MarkH-UK** [comment]
@imranz please review plurals and string-arrays in MiuiMusic/phone/res/values-ms/strings.xml

**Comment by imranz** [comment]
complete translated MiuiMusic strings xml
