### ISSUE TITLE
Notes package (review strings / string-arrays and plurals)

### ISSUE THREAD

**Issue by MarkH-UK** [MiCode/i18n_miui#41]
Imran to review and assign plurals and arrays translations for:

https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Notes/res/values-ms/strings.xml

and

https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Notes/res/values-ms/arrays.xml

**Comment by imranz** [comment]
fix translation Notes arrays and strings xml
