### ISSUE TITLE
Settings package 100% strings (string-arrays / plurals to be reviewed)

### ISSUE THREAD

**Issue by MarkH-UK** [MiCode/i18n_miui#50]
Imran to assign translation task for the following file (where applicable to translate items)...

https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Settings/res/values-ms/arrays.xml

Also review plurals and string-arrays in strings.xml here: https://github.com/MiCode/i18n_miui/blob/master/aries/packages/apps/Settings/res/values-ms/strings.xml

**Comment by imranz** [comment]
done translated Settings Array xml
