### ISSUE TITLE
Framework base translations (minor work)

### ISSUE THREAD

**Issue by MarkH-UK** [MiCode/i18n_miui#70]
Imran to review and assign these files listed in the links below for translation (where applicable including arrays.xml and strings.xml + string-arrays / plurals)

https://github.com/MiCode/i18n_miui/tree/master/aries/frameworks/miui/packages/ApiDemos/res/values-ms

https://github.com/MiCode/i18n_miui/blob/master/aries/frameworks/miui/packages/DataHubProvider/res/values-ms/strings.xml

https://github.com/MiCode/i18n_miui/blob/master/aries/frameworks/miui/packages/V5Demos/res/values-ms/strings.xml

https://github.com/MiCode/i18n_miui/blob/master/aries/frameworks/base/packages/BackupRestoreConfirmation/res/values-ms/strings.xml

https://github.com/MiCode/i18n_miui/blob/master/aries/frameworks/base/packages/SystemUI/res/values-ms/strings.xml

https://github.com/MiCode/i18n_miui/blob/master/aries/frameworks/base/packages/VpnDialogs/res/values-ms/strings.xml

**Comment by imranz** [comment]
https://github.com/MiCode/i18n_miui/blob/master/aries/frameworks/miui/packages/DataHubProvider/res/values-ms/strings.xml

Task done

**Comment by imranz** [comment]
https://github.com/MiCode/i18n_miui/blob/master/aries/frameworks/miui/packages/V5Demos/res/values-ms/strings.xml

Task done

**Comment by imranz** [comment]
https://github.com/MiCode/i18n_miui/blob/master/aries/frameworks/base/packages/SystemUI/res/values-ms/strings.xml

Task done
