### ISSUE TITLE
Organise workflow for Milestone #2

### ISSUE THREAD

**Issue by MarkH-UK** [MiCode/i18n_miui#76]
Organise patches and coordinate with translation team to ensure new resource strings are added on a weekly scheduled basis.

**Comment by mattandryc** [comment]
yes, me and Wuna will discuss this with Gary

**Comment by mattandryc** [comment]
also, at least for the debug phase of the ms alpha a string freeze will in place as of Friday 1/25. no new material will be added during the debug

**Comment by MarkH-UK** [comment]
@mattandryc agree with Repo / Code freeze for 1/25.
